name: Run tests and upload to Qase

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --api-url=https://restful-booker.herokuapp.com --junitxml=results.xml

    - name: Upload test results to Qase
      run: |
        python qase_config.py
      env:
        QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
