name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
<<<<<<< HEAD
        python-version: '3.12'
=======
        python-version: '3.8'
>>>>>>> 25a8334 (Integrate QASE with CI/CD)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install qaseio

    - name: Run tests
      run: |
        pytest tests/ --junitxml=results.xml

    - name: Upload test results to QASE
      run: |
<<<<<<< HEAD
        python upload_qase_results.py
=======
        python qase_config.py
>>>>>>> 25a8334 (Integrate QASE with CI/CD)
      env:
        QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
